apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-dmaap-kafka-configmap.name" . }}-server-prop-configmap
  labels:
    app: {{ template "eric-oss-dmaap-kafka-configmap.name" . }}
  {{- include "eric-oss-dmaap-kafka.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-dmaap-kafka.helm-annotations" .| nindent 4 }}
data:
{{ tpl (.Files.Glob "resources/config/server.properties").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-dmaap-kafka-configmap.name" . }}-cadi-prop-configmap
  labels:
    app: {{ template "eric-oss-dmaap-kafka-configmap.name" . }}
  {{- include "eric-oss-dmaap-kafka.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-dmaap-kafka.helm-annotations" .| nindent 4 }}
data:
{{ tpl (.Files.Glob "resources/config/cadi.properties").AsConfig . | indent 2 }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-dmaap-kafka-configmap.name" . }}-log4j-prop-configmap
  labels:
    app: {{ template "eric-oss-dmaap-kafka-configmap.name" . }}
  {{- include "eric-oss-dmaap-kafka.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-dmaap-kafka.helm-annotations" .| nindent 4 }}
data:
{{ tpl (.Files.Glob "resources/config/log4j.properties").AsConfig . | indent 2 }}
---

