apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-oss-dmaap-kafka-service-hs.name" . }}
  labels:
    app: {{ template "eric-oss-dmaap-kafka-service-hs.name" . }}
  {{- include "eric-oss-dmaap-kafka.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-dmaap-kafka.helm-annotations" .| nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.internalPort }}
      name: {{ .Values.service.portName }}
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}

